stages:
  - build
  - publish

default:
  image: node:20.11.0-alpine
  services:
    - docker:26.1.4-dind
  before_script:
    - npm ci

build_application:
  stage: build
  script:
    - npm run build --prod
    - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG .
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""

publish_application:
  stage: publish
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""